---
# Worker node specific variables

# Kubelet extra arguments
kubelet_extra_args: {}
  # max-pods: "110"
  # pod-infra-container-image: registry.k8s.io/pause:3.9

# Node labels for worker nodes
worker_node_labels:
  node-role.kubernetes.io/worker: "worker"

# Node taints (empty by default)
worker_node_taints: []
